const path = require('path');
const fs = require('fs');
const { info, warn } = require('./utils');

const KNOWN_NATIVE = [
  'bcrypt', 'sharp', 'sqlite3', 'better-sqlite3',
  'node-gyp', 'canvas', 'node-pty', 'cpu-features',
  'bcryptjs', 'oracledb', 'ibm_db',
];

const PURE_JS_ALTERNATIVES = {
  bcrypt: 'bcryptjs (纯 JS)',
  sharp: null,
  sqlite3: 'better-sqlite3 (仍需原生)',
  canvas: null,
};

function detectNativeInTree(cwd = process.cwd()) {
  const found = [];
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) return found;

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

  for (const name of KNOWN_NATIVE) {
    if (allDeps[name]) {
      found.push({ name, version: allDeps[name], suggest: PURE_JS_ALTERNATIVES[name] || null });
    }
  }

  // Check for Prisma (has native query engine)
  if (allDeps['@prisma/client'] || allDeps.prisma) {
    found.push({ name: '@prisma/client (Prisma Query Engine 是原生二进制)', version: allDeps['@prisma/client'] || 'latest', suggest: null });
  }

  return found;
}

function generateSidecarPackageJson(nativePackages, originalPkg) {
  const deps = {};
  for (const pkg of nativePackages) {
    const name = pkg.name.split(' ')[0];
    const version = originalPkg?.dependencies?.[name] || originalPkg?.devDependencies?.[name] || 'latest';
    if (!name.startsWith('@prisma')) {
      if (name === 'bcrypt') deps[name] = version;
      else deps[name] = version;
    } else {
      deps['@prisma/client'] = originalPkg?.dependencies?.['@prisma/client'] || 'latest';
    }
  }

  return {
    name: originalPkg?.name ? `${originalPkg.name}-sidecar` : 'app-sidecar',
    version: '1.0.0',
    private: true,
    description: 'Sidecar package.json for native modules (generated by node-jar)',
    dependencies: deps,
  };
}

function writeSidecar(nativePackages, outputDir, originalPkg) {
  const sidecarDir = path.dirname(outputDir);
  const sidecarPkg = generateSidecarPackageJson(nativePackages, originalPkg);
  const sidecarPath = path.join(sidecarDir, 'package.json');

  fs.writeFileSync(sidecarPath, JSON.stringify(sidecarPkg, null, 2));

  warn(`检测到 ${nativePackages.length} 个原生模块，已启用 sidecar 模式:`);
  for (const pkg of nativePackages) {
    warn(`  - ${pkg.name}`);
    if (pkg.suggest) warn(`    建议替代: ${pkg.suggest}`);
  }
  info('');
  info('部署步骤:');
  info(`  1. 上传 dist/ 目录到服务器`);
  info(`  2. cd dist && npm install --production  (仅安装原生依赖，几秒完成)`);
  info(`  3. node app.bundle.js`);
}

module.exports = { detectNativeInTree, writeSidecar };
